services:
  - type: web
    name: uptask-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        value: your-mongo-uri-here
