services:
  - type: web
    name: uptask-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        value: mongodb+srv://root:<v8W_ZnTAPaakGQ2>@cluster0.ndi1c.mongodb.net/
